/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : string,
  'title' : string,
  'dueDate' : string,
  'description' : string,
  'subjectId' : string,
}
export interface AudioChunk {
  'data' : Uint8Array,
  'senderUsername' : string,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface Grade {
  'id' : string,
  'studentId' : string,
  'feedback' : string,
  'score' : bigint,
  'assignmentId' : string,
}
export interface StudentProfile {
  'id' : string,
  'username' : string,
  'name' : string,
  'passwordHash' : string,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'description' : string,
  'teacherPrincipal' : string,
}
export interface VoiceSession {
  'id' : string,
  'participants' : Array<string>,
  'isActive' : boolean,
  'hostUsername' : string,
}
export interface _SERVICE {
  'addGrade' : ActorMethod<[string, string, bigint, string], string>,
  'checkVerificationCode' : ActorMethod<[string, string], boolean>,
  'createAssignment' : ActorMethod<[string, string, string, string], string>,
  'createSubject' : ActorMethod<[string, string, string], string>,
  'createVoiceSession' : ActorMethod<[string, string], undefined>,
  'endVoiceSession' : ActorMethod<[string], undefined>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getGradesByStudent' : ActorMethod<[string], Array<Grade>>,
  'getStudentById' : ActorMethod<[string], [] | [StudentProfile]>,
  'getStudentPublicByUsername' : ActorMethod<[string], [] | [[string, string]]>,
  'getVoiceSession' : ActorMethod<[string], [] | [VoiceSession]>,
  'joinVoiceSession' : ActorMethod<[string, string], undefined>,
  'listActiveVoiceSessions' : ActorMethod<[], Array<VoiceSession>>,
  'loginStudent' : ActorMethod<
    [string, string],
    { 'ok' : StudentProfile } |
      { 'err' : string }
  >,
  'pollAudioChunks' : ActorMethod<[string, bigint, string], Array<AudioChunk>>,
  'registerStudent' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendAudioChunk' : ActorMethod<[string, string, Uint8Array], undefined>,
  'setVerificationCode' : ActorMethod<[string, string], undefined>,
  'studentExistsInBackend' : ActorMethod<[string], boolean>,
  'studentHasVerificationCode' : ActorMethod<[string], boolean>,
  'syncStudentForParentLink' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];