/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'teacherPrincipal' : IDL.Text,
});
export const Grade = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'assignmentId' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'name' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const VoiceSession = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'hostUsername' : IDL.Text,
});
export const AudioChunk = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'senderUsername' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGrade' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'checkVerificationCode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'createAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createVoiceSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'endVoiceSession' : IDL.Func([IDL.Text], [], []),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getGradesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Grade)], ['query']),
  'getStudentById' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], ['query']),
  'getStudentPublicByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getVoiceSession' : IDL.Func([IDL.Text], [IDL.Opt(VoiceSession)], ['query']),
  'joinVoiceSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'listActiveVoiceSessions' : IDL.Func([], [IDL.Vec(VoiceSession)], ['query']),
  'loginStudent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : StudentProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'pollAudioChunks' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text],
      [IDL.Vec(AudioChunk)],
      ['query'],
    ),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendAudioChunk' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'setVerificationCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'studentExistsInBackend' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'studentHasVerificationCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'syncStudentForParentLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'teacherPrincipal' : IDL.Text,
  });
  const Grade = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'assignmentId' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'name' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const VoiceSession = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'hostUsername' : IDL.Text,
  });
  const AudioChunk = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'senderUsername' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
  });
  
  return IDL.Service({
    'addGrade' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'checkVerificationCode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'createAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createVoiceSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'endVoiceSession' : IDL.Func([IDL.Text], [], []),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getGradesByStudent' : IDL.Func([IDL.Text], [IDL.Vec(Grade)], ['query']),
    'getStudentById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getStudentPublicByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getVoiceSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VoiceSession)],
        ['query'],
      ),
    'joinVoiceSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'listActiveVoiceSessions' : IDL.Func(
        [],
        [IDL.Vec(VoiceSession)],
        ['query'],
      ),
    'loginStudent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : StudentProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'pollAudioChunks' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text],
        [IDL.Vec(AudioChunk)],
        ['query'],
      ),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendAudioChunk' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'setVerificationCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'studentExistsInBackend' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'studentHasVerificationCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'syncStudentForParentLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };