/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Grade {
    id: string;
    studentId: string;
    feedback: string;
    score: bigint;
    assignmentId: string;
}
export interface Assignment {
    id: string;
    title: string;
    dueDate: string;
    description: string;
    subjectId: string;
}
export interface VoiceSession {
    id: string;
    participants: Array<string>;
    isActive: boolean;
    hostUsername: string;
}
export interface StudentProfile {
    id: string;
    username: string;
    name: string;
    passwordHash: string;
}
export interface Subject {
    id: string;
    name: string;
    description: string;
    teacherPrincipal: string;
}
export interface AudioChunk {
    data: Uint8Array;
    senderUsername: string;
    timestamp: bigint;
    sessionId: string;
}
export interface backendInterface {
    addGrade(studentId: string, assignmentId: string, score: bigint, feedback: string): Promise<string>;
    checkVerificationCode(username: string, code: string): Promise<boolean>;
    createAssignment(subjectId: string, title: string, description: string, dueDate: string): Promise<string>;
    createSubject(name: string, description: string, teacherPrincipal: string): Promise<string>;
    createVoiceSession(sessionId: string, hostUsername: string): Promise<void>;
    endVoiceSession(sessionId: string): Promise<void>;
    fetchWordPressContent(baseUrl: string, endpoint: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllAssignments(): Promise<Array<Assignment>>;
    getAllSubjects(): Promise<Array<Subject>>;
    getGradesByStudent(studentId: string): Promise<Array<Grade>>;
    getStudentById(id: string): Promise<StudentProfile | null>;
    getStudentPublicByUsername(username: string): Promise<[string, string] | null>;
    getTeacherWpUrl(): Promise<string>;
    getVoiceSession(sessionId: string): Promise<VoiceSession | null>;
    joinVoiceSession(sessionId: string, username: string): Promise<void>;
    listActiveVoiceSessions(): Promise<Array<VoiceSession>>;
    loginStudent(username: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: StudentProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    pollAudioChunks(sessionId: string, sinceTimestamp: bigint, excludeUsername: string): Promise<Array<AudioChunk>>;
    registerStudent(username: string, name: string, passwordHash: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendAudioChunk(sessionId: string, senderUsername: string, data: Uint8Array): Promise<void>;
    setTeacherWpUrl(url: string): Promise<void>;
    setVerificationCode(username: string, code: string): Promise<void>;
    studentExistsInBackend(username: string): Promise<boolean>;
    studentHasVerificationCode(username: string): Promise<boolean>;
    syncStudentForParentLink(username: string, name: string, code: string): Promise<void>;
}
import type { StudentProfile as _StudentProfile, VoiceSession as _VoiceSession } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGrade(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addGrade(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGrade(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async checkVerificationCode(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkVerificationCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkVerificationCode(arg0, arg1);
            return result;
        }
    }
    async createAssignment(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSubject(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0, arg1, arg2);
            return result;
        }
    }
    async createVoiceSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoiceSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoiceSession(arg0, arg1);
            return result;
        }
    }
    async endVoiceSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endVoiceSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endVoiceSession(arg0);
            return result;
        }
    }
    async fetchWordPressContent(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchWordPressContent(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchWordPressContent(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignments();
            return result;
        }
    }
    async getAllSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubjects();
            return result;
        }
    }
    async getGradesByStudent(arg0: string): Promise<Array<Grade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradesByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradesByStudent(arg0);
            return result;
        }
    }
    async getStudentById(arg0: string): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentById(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentById(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentPublicByUsername(arg0: string): Promise<[string, string] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentPublicByUsername(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentPublicByUsername(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherWpUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherWpUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherWpUrl();
            return result;
        }
    }
    async getVoiceSession(arg0: string): Promise<VoiceSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceSession(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceSession(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinVoiceSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinVoiceSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinVoiceSession(arg0, arg1);
            return result;
        }
    }
    async listActiveVoiceSessions(): Promise<Array<VoiceSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveVoiceSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveVoiceSessions();
            return result;
        }
    }
    async loginStudent(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: StudentProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginStudent(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginStudent(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async pollAudioChunks(arg0: string, arg1: bigint, arg2: string): Promise<Array<AudioChunk>> {
        if (this.processError) {
            try {
                const result = await this.actor.pollAudioChunks(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pollAudioChunks(arg0, arg1, arg2);
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendAudioChunk(arg0: string, arg1: string, arg2: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAudioChunk(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAudioChunk(arg0, arg1, arg2);
            return result;
        }
    }
    async setTeacherWpUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTeacherWpUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTeacherWpUrl(arg0);
            return result;
        }
    }
    async setVerificationCode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVerificationCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVerificationCode(arg0, arg1);
            return result;
        }
    }
    async studentExistsInBackend(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.studentExistsInBackend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.studentExistsInBackend(arg0);
            return result;
        }
    }
    async studentHasVerificationCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.studentHasVerificationCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.studentHasVerificationCode(arg0);
            return result;
        }
    }
    async syncStudentForParentLink(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.syncStudentForParentLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncStudentForParentLink(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[string, string]]): [string, string] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoiceSession]): VoiceSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StudentProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StudentProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
